# conda env create -f environment.yml
name: daops
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - numpy>=1.16
  - xarray>=0.15
  - dask
  - netcdf4
  - clisops>=0.4.0
  - elasticsearch>=7.9.1
  - udunits2>=2.2
  - roocs_utils>=0.1.4
