# conda env create -f environment.yml
name: daops
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - numpy>=1.16
  - xarray>=0.15
  - dask
  - netcdf4
  - clisops>=0.6.1
  - elasticsearch>=7.9.1
  #- roocs-utils>=0.2.1
  # catalog
  - pywps>=4.4.2,<4.5
  - intake
  - fsspec<0.9
  - pandas
  - aiohttp
  - pip:
    - roocs-utils @ git+https://github.com/roocs/roocs-utils.git@master#egg=roocs-utils
#     - clisops @ git+https://github.com/roocs/clisops.git@master#egg=clisops
