# conda env create -f environment.yml
name: daops
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pip
  # daops
  - xarray>=0.15
  - dask
  - netcdf4
  - rtree>=0.9
  - udunits2>=2.2
  # - clisops>=0.2.0,<0.3
  # tests
  - pytest
  - pip:
    - roocs-utils>=0.1.4
    - -e git+https://github.com/roocs/clisops.git@master#egg=clisops
