# conda env create -f environment.yml
name: daops
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - numpy>=1.16
  - xarray>=2023.7.0
  - dask
  - netcdf4
  - clisops>=0.9.1
  - elasticsearch>=7.9.1
#  - roocs-utils>=0.6.2
  # logging
  - loguru>=0.5.3
  # catalog
  - intake
  # to support kerchunk
  - fsspec==2022.11.0
  - aiohttp
  - zstd
  - pip:
    - git+https://github.com/roocs/roocs-utils.git@i106-enable-read-kerchunk#egg=roocs_utils
