# conda env create -f environment.yml
name: daops
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pip
  # daops
  - xarray>=0.15
  - dask
  - netcdf4
  clisops>=0.2.0,<0.3
  # tests
  - pytest
  - pip:
    - -e git+https://github.com/roocs/roocs-utils.git@master#egg=roocs_utils
