# conda env create -f environment.yml
name: daops-docs
channels:
  - conda-forge
  - defaults
dependencies:
  - sphinx
  - nbsphinx
  - ipython
  - pandoc
  - pip
  - numpy>=1.16
  - xarray>=0.15
  - dask
  - netcdf4
  - rtree>=0.9
  - udunits2>=2.2
  - clisops>=0.3.0
  - elasticsearch>=7.9.1
